### ISSUE TITLE
Application bootup is very slow when using either intellij or maven to run

### ISSUE THREAD

**Issue by bpg168** [bpg168/trainticket#2]
Currently, the slowness seems to be originating from the liquibase changelog applying, however, there could be different reasons.

Logs, the two lines where 10seconds is spent is shown by adding newlines before and after (however they are all continuous logs, no log lines deleted in between)
```
11:30:26.348 281897 [main] INFO  liquibase.database - Set default schema name to PUBLIC
11:30:26.357 281897 [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After adding stats (total=10, active=1, idle=9, waiting=0)


11:30:26.737 281897 [main] INFO  liquibase.changelog - Creating database history table with name: PUBLIC.DATABASECHANGELOG
11:30:36.815 281897 [main] INFO  liquibase.changelog - Reading from PUBLIC.DATABASECHANGELOG


11:30:36.844 281897 [main] INFO  liquibase.lockservice - Successfully acquired change log lock
11:30:36.845 281897 [main] INFO  liquibase.command - Using deploymentId: 2383236844
11:30:36.846 281897 [main] INFO  liquibase.changelog - Reading from PUBLIC.DATABASECHANGELOG
Running Changeset: db/changelog/create-trainticket-db.xml::1::trainticket-server
11:30:36.881 281897 [main] INFO  liquibase.changelog - Custom SQL executed
11:30:36.882 281897 [main] INFO  liquibase.changelog - ChangeSet db/changelog/create-trainticket-db.xml::1::trainticket-server ran successfully in 27ms
Running Changeset: db/changelog/populate-init-data.xml::1::trainticket-server
11:30:36.891 281897 [main] INFO  liquibase.changelog - Custom SQL executed
11:30:36.891 281897 [main] INFO  liquibase.changelog - ChangeSet db/changelog/populate-init-data.xml::1::trainticket-server ran successfully in 4ms
11:30:36.895 281897 [main] INFO  liquibase.util - UPDATE SUMMARY
11:30:36.895 281897 [main] INFO  liquibase.util - Run:                          2
11:30:36.895 281897 [main] INFO  liquibase.util - Previously run:               0
11:30:36.895 281897 [main] INFO  liquibase.util - Filtered out:                 0
11:30:36.895 281897 [main] INFO  liquibase.util - -------------------------------
11:30:36.895 281897 [main] INFO  liquibase.util - Total change sets:            2
11:30:36.895 281897 [main] INFO  liquibase.util - Update summary generated
11:30:36.896 281897 [main] INFO  liquibase.command - Update command completed successfully.
Liquibase: Update has been successful. Rows affected: 3
11:30:36.898 281897 [main] INFO  liquibase.lockservice - Successfully released change log lock
11:30:36.899 281897 [main] INFO  liquibase.command - Command execution complete
```

**Comment by bpg168** [comment]
Weirdly the issue is something to do with resolving IPv6 to localhost.. Happening in the liquibase library.

Reported here by commenting with details in an existing thread:
https://github.com/liquibase/liquibase/issues/2440#issuecomment-2041022292


It was able to debug simply by taking a few thread dumps repeatedly, as the program is anyway hanging for ~10 seconds.


Stacktrace for ref
```
"main" #1 prio=5 os_prio=0 cpu=2605.16ms elapsed=4.23s tid=0x0000739db8025580 nid=0x4849a runnable  [0x0000739dbdf10000]
   java.lang.Thread.State: RUNNABLE
        at java.net.Inet6AddressImpl.getHostByAddr(java.base@17.0.8/Native Method)
        at java.net.InetAddress$PlatformNameService.getHostByAddr(java.base@17.0.8/InetAddress.java:940)
        at java.net.InetAddress.getHostFromNameService(java.base@17.0.8/InetAddress.java:662)
        at java.net.InetAddress.getHostName(java.base@17.0.8/InetAddress.java:605)
        at java.net.InetAddress.getHostName(java.base@17.0.8/InetAddress.java:577)
        at liquibase.util.NetUtil.getLocalHostName(NetUtil.java:79)
        at liquibase.sqlgenerator.core.LockDatabaseChangeLogGenerator.<clinit>(LockDatabaseChangeLogGenerator.java:30)
```


Command for ref for fast thread dumps by repeatedly hitting in terminal
```
jstack $(jps | grep train | awk '{print $1}') > $(date '+%H_%M_%S')_stack.txt
```

**Comment by bpg168** [comment]
**Tried for fun only**
Definitely not adviceable to write code like this..

The source code for the `liquibase.util.NetUtil.getLocalHostName` starts as,
```
    public static String getLocalHostName() {
        if (hostName == null) {
                //... the slow code is here..//
```
So if we somehow make the `hostName`  field non null, we get around the issue,
```
public class NetUtil {
    private static InetAddress localHost;
    private static String hostName;
    private static final String UNKNOWN_HOST_NAME = "unknown";
```
As it is a private static field, let's use reflection to make the field accessible and set it..

```
Field field = NetUtil.class.getDeclaredField("hostName");
field.setAccessible(true);
field.set(null, "localhost");
field.setAccessible(false);
```

I don't think this kind of code should go to production...
